Verify server signature
hyperledger-labs/orion-sdk-go pull request #84
Opened 2021-11-18 15:02 UTC by tohar-ayash

2021-11-24 15:23 UTC, gennadylaventman commented
I think you need unit test for that.

2021-11-24 15:23 UTC, gennadylaventman reviewed
Lets add unit test here.

2021-12-09 07:26 UTC, tock-ibm commented
Look for the TODO comments in the code, many of them have `TODO signature verification` 
address these places in the code where you find these.

I think also there needs to be a testcase on every context type (data, user, admin, config, json-query, provenance, etc) that tests signature verification, i.e. it fails if the signature is wrong.

2021-12-09 07:55 UTC, gennadylaventman requested changes

2021-12-09 07:55 UTC, gennadylaventman commented on pkg/bcdb/tx_context_test.go
> +	emptySigner := &mocks.Signer{}
This is overkill. You create all this mock infrastructure, but actually don't use it in test. Just calling to `ResponseSelector` twice, one with correct envelope and one with in-correct, will be enough.

2021-12-09 08:42 UTC, tohar-ayash commented on pkg/bcdb/tx_context_test.go
> +	emptySigner := &mocks.Signer{}
Done

2021-12-09 08:57 UTC, gennadylaventman approved these changes

2021-12-09 08:57 UTC, merged